### ISSUE TITLE
Compilation error on OpenSUSE

### ISSUE THREAD

**Issue by rickhelmus** [lionel-/freetypeharfbuzz#4]
Hello,

At the moment I cannot install this package because of a compilation error about a missing library:
```
/tmp/RtmpUY5G7N/R.INSTALL472750f70e4e/freetypeharfbuzz/src/target/lib/libharfbuzz.a
```
The actual library is there, it's just in the **lib64/** directory. A workaround is to symlink this directory to lib/ and re-run `devtools::install()` with `build = FALSE`.

Cheers,
Rick

**Comment by tpilz** [comment]
Thanks for the hint, I had the same problem.

**Comment by rickhelmus** [comment]
I had some trouble applying this workaround with R 3.6; editing `src/Makevars.in` worked though:
```r
LIB_DIR = $(TARGET_DIR)/lib64
```

**Comment by TimTaylor** [comment]
Just got the same error on TumbleWeed.  Couldn't work the fix out.

**Comment by lionel-** [comment]
Note that freetypeharfbuzz is not needed for any real user-facing task. It's only used in vdiffr for unit-testing graphical packages like ggplot.

Since this package embeds foreign code that causes SAN warnings (these won't be fixed upstream), I'm unlikely to send an update to CRAN unless it's really needed, because the CRAN maintainers might take the opportunity to require the warnings to be fixed.

**Comment by TimTaylor** [comment]
Cheers for the reply. Got it working in the end. The workaround above still works in R 4.0:

> I had some trouble applying this workaround with R 3.6; editing `src/Makevars.in` worked though:
> 
> ```r
> LIB_DIR = $(TARGET_DIR)/lib64
> ```
